### ISSUE TITLE
Can the project export the onnx file?

### ISSUE THREAD

**Issue by scuizhibin** [mit-han-lab/bevfusion#18]

**Comment by kentang-mit** [comment]
Hi @scuizhibin,

It will be a bit hard to export the current model to ONNX because of the existence of custom CUDA ops (e.g. SparseConv, BEV pooling, etc). However, we'll work on the deployment of BEVFusion in the future, please stay tuned and we will send you the update once we have something new to release.

Best,
Haotian

**Comment by scuizhibin** [comment]
thank&nbsp;you


---Original---
From: &quot;Haotian (Ken) ***@***.***&gt;
Date: Fri, Jun 10, 2022 22:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mit-han-lab/bevfusion] Can the project export the onnx file?(Issue #18)




 
Hi @scuizhibin,
 
It will be a bit hard to export the current model to ONNX because of the existence of custom CUDA ops (e.g. SparseConv, BEV pooling, etc). However, we'll work on the deployment of BEVFusion in the future, please stay tuned and we will send you the update once we have something new to release.
 
Best,
 Haotian
 
&mdash;
