### ISSUE TITLE
inference speed in paper

### ISSUE THREAD

**Issue by AndyYuan96** [mit-han-lab/bevfusion#185]
Hi, you say the transfusion speed is  156.6 ms / frame in your paper, but in transfusion paper, the speed is 265.9ms/frame. So your guys just change gpu from v100 to 3090, and then speed up more than 100 ms?

**Comment by kentang-mit** [comment]
Our inference time is calculated by summing up the runtime of different components in the model (i.e. adding timers before and after modules, such as the LiDAR backbone, camera backbone, view transformer and BEV part). Specifically, we did not count the time for voxelization because the current implementation in mmdetection3d is very slow and it can be replaced with a dynamic voxelization implementation. 

We report the inference time of all methods in our paper using this protocol for fair comparison.
