### ISSUE TITLE
Question about the improvement calculation of multi-modality in ablation studies?

### ISSUE THREAD

**Issue by yt7589** [mit-han-lab/bevfusion#19]
In the paper 2205.13542 ablation studies section in the table 4.a, it said: the NDS score is 40.2 when use Camera mode only, and the NDS score is 69.5 when use Camera + Lidar mode. According to my understanding the improvement rate should be:
$$r =\frac{69.5 - 40.2}{40.2} = 0.73$$
But in the paper you said the improvement ratio is 6.6%. My question is How you get this number (6.6%) given the data in table 4.a?

**Comment by kentang-mit** [comment]
Hi @yt7589,

I think the 6.6% improvement refers to the BEVFusion (C+L) v.s. the camera-only baseline in the segmentation setting. In this paper we assume that if you want to compare fusion models with camera-only methods, you should use segmentation as the task. This is because camera-only detection mAP/NDS is a bit too low.

Best,
Haotian

**Comment by kentang-mit** [comment]
I'll temporarily close this issue. Feel free to reopen if you have further questions.
