### ISSUE TITLE
RuntimeError: /bevfusion-main/mmdet3d/ops/spconv/include/tensorview/helper_launch.h 17 N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0

### ISSUE THREAD

**Issue by youngfly** [mit-han-lab/bevfusion#297]
hello， i met a very strange problem as tiltle during the training.
This problem occurs in different epoch.
1)
![image](https://user-images.githubusercontent.com/30973033/216560360-4b5e16c1-b5a9-41ac-8965-a0212ba31a0c.png)
 
2)
![image](https://user-images.githubusercontent.com/30973033/216560466-429b8fac-25fd-44db-a998-df9c2462af88.png)

3)
![image](https://user-images.githubusercontent.com/30973033/216560575-911414a3-92a6-4053-a36b-bfbe11007458.png)

4) 
![image](https://user-images.githubusercontent.com/30973033/216560680-252f801c-6496-4e15-913b-3e16d37c8c7d.png)

problem
![image](https://user-images.githubusercontent.com/30973033/216560775-cfb74ccb-66f5-421a-b2cf-bc29157db1c9.png)

my CUDA version is 11.1.
GPU:Nvidia A100
pytorch:1.9.0
other required libraries are installed indicated in your README

**Comment by kentang-mit** [comment]
According to some previous discussions, it is possible that the error is caused by unmatched CUDA versions (between the OS and the anaconda environment). Would you mind checking what is the `cuda-toolkit` version you installed in anaconda? 
By the way, we are going to replace the spconv backend in the next release. Please stay tuned.

**Comment by youngfly** [comment]
I have sovled this problem with a new environment. It is very strange.
