### ISSUE TITLE
whether the number of gpus will influence performance or not?

### ISSUE THREAD

**Issue by hollow-503** [mit-han-lab/bevfusion#310]
Thanks for your great work! 
I want to reproduce your fusion model performance, but i only have **4 gpus**. I noticed that you train with **8 gpus**. According to some experiments, I found that the `batch size` will greatly influence performance. I am curious about whether the performance will be lower if I use **4 gpus** with `batch_size=4`. I am not familiar with `torchpack`, and I don't know if the training speed is the only difference between them.

**Comment by Monoclinic** [comment]
In my experience if you train use official lidar-only pretrain and only finetune the fusion model, bs=4*4 may cause a drop of ~0.3 mAP (68.52 -> ~68.22), while NDS will not decrease so much (71.38 -> ~71.3).
The lr is set to 1.0e-4 since batchsize is halved, maybe you can get a better performance by adjusting the training schedule.
