### ISSUE TITLE
Question about test-time augmentation and ensemble.

### ISSUE THREAD

**Issue by HatsuneMiku888** [mit-han-lab/bevfusion#4]
Hi~
Can you share the detailed configuration about TTA and model ensemble?
I notice that these tricks bring the significant gains, but I haven’t find relative code in this repo.
Thanks!

**Comment by kentang-mit** [comment]
Hi @HatsuneMiku888,

Thanks for the interest. I think TTA and model ensemble are not in the short-term release plan, since we do have higher priority release items, and other research papers typically only compare the results without these additional tricks. However, if you want to reproduce TTA and model ensemble, I would recommend you have a look at the appendix of [CenterPoint](https://arxiv.org/pdf/2006.11275.pdf) and Tianwei's GitHub issues.

Best,
Haotian
